# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "alfetest-app-2"
client_id = "4ec0aad948077d8b39639f9ce9817a25"
application_url = "https://counter-cables-clocks-sale.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://counter-cables-clocks-sale.trycloudflare.com/auth/callback",
  "https://counter-cables-clocks-sale.trycloudflare.com/auth/shopify/callback",
  "https://counter-cables-clocks-sale.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "clevelandrocks.myshopify.com"
